# Generated by Django 5.0 on 2023-12-25 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='date_of_creation',
            new_name='date_create',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='is_image',
            new_name='published',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='text',
        ),
    ]
