# Generated by Django 5.0 on 2024-01-17 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_product_email_sphere_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('category_name',), 'verbose_name': 'категория', 'verbose_name_plural': 'категории'},
        ),
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ('name',), 'verbose_name': 'сообщение', 'verbose_name_plural': 'сообщения'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('product_name',), 'verbose_name': 'продукт', 'verbose_name_plural': 'продукты'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='email',
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.IntegerField(verbose_name='номер версии')),
                ('name', models.CharField(verbose_name='название версии')),
                ('is_active', models.BooleanField(verbose_name='активная версия')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prod', to='catalog.product', verbose_name='продукт')),
            ],
            options={
                'verbose_name': 'версия',
                'verbose_name_plural': 'версии',
                'ordering': ('product',),
            },
        ),
    ]
