# Generated by Django 5.0 on 2024-01-18 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_category_options_alter_feedback_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sphere',
        ),
    ]
